include_guard(GLOBAL)

# Keep the host layout used by Microsoft's native NuGet targets: an emulated
# application still needs the OpenConsole executable for the native OS CPU.
function(vnm_terminal_conpty_runtime_files output)
    get_property(package_dir GLOBAL PROPERTY vnm_terminal_conpty_package_dir)
    string(TOLOWER "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}" architecture)
    if(NOT architecture)
        string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" architecture)
    endif()
    if(architecture MATCHES "^(arm64|aarch64)$")
        set(architecture arm64)
        set(hosts arm64)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(architecture x64)
        set(hosts x64 arm64)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(architecture x86)
        set(hosts x86 x64 arm64)
    else()
        message(FATAL_ERROR "Unsupported ConPTY target architecture: ${architecture}")
    endif()
    set(files "runtimes/win-${architecture}/native/conpty.dll|conpty.dll")
    foreach(host IN LISTS hosts)
        list(APPEND files "build/native/runtimes/${host}/OpenConsole.exe|${host}/OpenConsole.exe")
    endforeach()
    list(APPEND files "LICENSE|licenses/conpty/LICENSE")
    foreach(file IN LISTS files)
        string(REPLACE "|" ";" parts "${file}")
        list(GET parts 0 source)
        if(NOT EXISTS "${package_dir}/${source}")
            message(FATAL_ERROR "ConPTY package is missing ${package_dir}/${source}")
        endif()
    endforeach()
    set(${output} "${files}" PARENT_SCOPE)
endfunction()

function(vnm_terminal_deploy_conpty target)
    if(NOT WIN32)
        return()
    endif()
    get_property(package_dir GLOBAL PROPERTY vnm_terminal_conpty_package_dir)
    vnm_terminal_conpty_runtime_files(files)
    foreach(file IN LISTS files)
        string(REPLACE "|" ";" parts "${file}")
        list(GET parts 0 source)
        list(GET parts 1 destination)
        get_filename_component(directory "${destination}" DIRECTORY)
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:${target}>/${directory}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${package_dir}/${source}" "$<TARGET_FILE_DIR:${target}>/${destination}"
            VERBATIM)
    endforeach()
endfunction()

function(vnm_terminal_install_conpty)
    if(NOT WIN32)
        return()
    endif()
    cmake_parse_arguments(arg "EXCLUDE_FROM_ALL" "DESTINATION;COMPONENT" "" ${ARGN})
    set(options)
    if(arg_COMPONENT)
        list(APPEND options COMPONENT "${arg_COMPONENT}")
    endif()
    if(arg_EXCLUDE_FROM_ALL)
        list(APPEND options EXCLUDE_FROM_ALL)
    endif()
    get_property(package_dir GLOBAL PROPERTY vnm_terminal_conpty_package_dir)
    vnm_terminal_conpty_runtime_files(files)
    foreach(file IN LISTS files)
        string(REPLACE "|" ";" parts "${file}")
        list(GET parts 0 source)
        list(GET parts 1 destination)
        get_filename_component(directory "${destination}" DIRECTORY)
        install(FILES "${package_dir}/${source}" DESTINATION "${arg_DESTINATION}/${directory}" ${options})
    endforeach()
endfunction()
