cmake_minimum_required(VERSION 3.21)

set_property(GLOBAL PROPERTY vnm_terminal_conpty_package_dir "${package_dir}")
include("${helper_file}")
vnm_terminal_conpty_runtime_files(files)

foreach(file IN LISTS files)
    string(REPLACE "|" ";" parts "${file}")
    list(GET parts 0 source)
    list(GET parts 1 destination)
    if(NOT EXISTS "${runtime_dir}/${destination}")
        message(FATAL_ERROR "ConPTY runtime is missing ${runtime_dir}/${destination}")
    endif()
    file(SHA256 "${package_dir}/${source}" expected_hash)
    file(SHA256 "${runtime_dir}/${destination}" deployed_hash)
    if(NOT expected_hash STREQUAL deployed_hash)
        message(FATAL_ERROR "ConPTY runtime does not match selected package: ${destination}")
    endif()
endforeach()
